### ISSUE TITLE
Pass the page URL as an arg to the thing engine

### ISSUE THREAD

**Issue by terrycojones** [fluidinfo/loveme.do-chrome#1]
Add something like URL=http...  to the URI we use to go to the thing engine. That will give it more context to use in deciding what to do.

**Comment by paparent** [comment]
We have the same mind again. I thought of sending this from my bookmarklet..
Actually an issue/idea should be created on fluidinfo.com about that. I
will be really useful.

**Comment by terrycojones** [comment]
I just verified (using nc) that the Chrome extension is not sending an Referrer header. The only time I got it to send one it sent the URL of the robots.txt file of the site I was looking at. So we need to do this properly / reliably ourselves.
