### ISSUE TITLE
The sidebar shows a vertical scrollbar even if it's not needed

### ISSUE THREAD

**Issue by terrycojones** [fluidinfo/loveme.do-chrome#104]
The sidebar always seems to display a vertical sidebar. Fix.

**Comment by jkakar** [comment]
This current behaviour is intentional.  It because of the `overflow-y:
scroll` in `extension.less`.  I put it there because otherwise the
scrollbar appears when comments load which causes the content to be
reflowed and you get weird flickering and other ugly rendering
artefacts.

**Comment by jkakar** [comment]
The object browser is the same, by the way, for the same reason.

**Comment by terrycojones** [comment]
OK, closing.
