### ISSUE TITLE
Open existing obrowser tab instead of new one

### ISSUE THREAD

**Issue by gridaphobe** [fluidinfo/loveme.do-chrome#42]
When the extension takes me to the obrowser, it always does so in a new tab. I'm not sure how other people use browsers, but I generally prefer to have one tab open per domain, unless I'm opening a bunch of articles to read.

I'd like to see an option to have the extension search for an existing fi.com tab and load the appropriate object there, instead of opening a brand new tab. I think this should be possible.

**Comment by jkakar** [comment]
@gridaphobe, I would find that behaviour really frustrating.  What do
you think about making the browser open in the same tab as the page
you're viewing?  If you want to open a new tab you can hold `Ctrl`
when you click the link.

**Comment by gridaphobe** [comment]
@jkakar I would actually find _that_ frustrating.. I think it's pretty
clear now that we need a few options, so users can choose to 
have the extension load objects in:
1. The current tab
2. A new tab
3. An existing fi.com tab, falling back to 1 or 2 if none exist.

**Comment by terrycojones** [comment]
I think this can be closed as a wontfix.  Now that we have the sidebar, and it drives the currently open tab, I don't think it makes sense to have it look for an existing tab.  It could be done, but I think it's (very) non-standard and potentially confusing and it would add another option. Eric - you can always maintain a fork :-)

**Comment by terrycojones** [comment]
Closing.
