### ISSUE TITLE
Add support for custom notification content via per domain javascript

### ISSUE THREAD

**Issue by terrycojones** [fluidinfo/loveme.do-chrome#62]
This will perhaps be controversial....

Make the extension look for `fluidinfo.com/display-javascript` tags in FluidDB. When it finds them, the about values that they're on will be treated as namespaces. The contents of the tag will be `eval`'d and used to produce display HTML for that namespace.

E.g., we put some javascript into a `fluidinfo.com/display-javascript` on the object with about value `oreilly.com`. When the user looks at an object with any `oreilly.com/xxxx` tag on it, the object's tags & values are passed to the Javascript (which we will have eval'd to get a function). The result is shown in the notification instead of the raw tags and values.

**Comment by terrycojones** [comment]
Hmmmm... I think I'll start this by at first just embedding the JS for a domain into a static JS object in the extension. Once that's working we can think about looking up the code dynamically.

**Comment by jkakar** [comment]
Is this to avoid having to publish a new version of the extension
whenever you have some content you want to handle in a particular way?

**Comment by terrycojones** [comment]
It's mainly to deal more sensibly with a large collection of related tags on the same object (possibly all from the same domain, possibly personal or social ones (like you own this oreilly book etc)).

There may be secondary benefits and dangers to moving to storing the JS in a tag on the domain object. But I'm not going to do that anytime soon.
